### ISSUE TITLE
ethchain.dnp.dappnode.eth: 0.1.14 should be allowed to update even if in sync

### ISSUE THREAD

**Issue by minerideseama** [dappnode/DNP_ADMIN#225]
*Before filing a new issue, please **provide the following information**.*

## Current versions
- **ethchain.dnp.dappnode.eth**: 0.1.14
- **admin.dnp.dappnode.eth**: 0.1.16
- **vpn.dnp.dappnode.eth**: 0.1.21
- **ethforward.dnp.dappnode.eth**: 0.1.5
- **dappmanager.dnp.dappnode.eth**: 0.1.20
- **ipfs.dnp.dappnode.eth**: 0.1.4
- **core.dnp.dappnode.eth**: 0.1.18
- **wifi.dnp.dappnode.eth**: 0.1.0
- **bind.dnp.dappnode.eth**: 0.1.6
- **wamp.dnp.dappnode.eth**: 0.1.1

## System info
- **Disk usage**: 10%
- **Docker version**: Docker version 17.05.0-ce, build v17.05.0-ce
- **Docker compose version**: docker-compose version 1.20.1, build 5d8c71b

Just a small opinion.
I was still in sync the main chain when the update appeared, but I wasn't allowed to update due to main chain not synced.
However, some updates could be very important security updates.
For example, if parity has an issue which is exploited that is preventing you to sync the chain, how can u fix if the update doesn't start because you are syncing the chain?
**I think ethchain package should be allowed to force update, maybe with user acceptance.**

Unrelated: **I think the --warp-barrier could be increased also to allow faster sync?**

Thank you!

**Comment by Shelpin** [comment]
Hi!!thanks for the feedback @minerideseama!! It is tricky because if mainet is not sync the eth domain won’t be solved...still you can force the ethchain update using the ipfs hash of the package in this case ipfs/QmebCzywYDtXvpeLFDBPW8LTGWk7RZqjnDBXRWpCbV5t22 .you can just type it in the above field of the installer screen and hit “by pass core restrictions”before installing.then you can update your ethereum client version without having the chain synced. Still we’ll think about it to improve this,as well as emphasizing it in the user doc.thanks!!
