### ISSUE TITLE
Link to a default url for the changelog in the installation preview page

### ISSUE THREAD

**Issue by eduadiez** [dappnode/DNP_ADMIN#242]

**Comment by dapplion** [comment]
- [ ] Implement: url sample https://github.com/dappnode/DNP_VPN/releases/tag/v0.1.21

**Comment by Shelpin** [comment]
![image](https://user-images.githubusercontent.com/21328788/60354868-88901480-99cd-11e9-9327-61a70423d443.png)

The link is there but in every case, it leads to an error page either because there is a random address in the link or because the directions looks nice but does not take anywhere 

![image](https://user-images.githubusercontent.com/21328788/60355024-d3119100-99cd-11e9-86b9-9f97e6868507.png)

**Comment by dapplion** [comment]
Thanks for picking up this. Fixed the typos causing these errors with https://github.com/dappnode/DNP_ADMIN/pull/332.
Can you reinstall the branch `v0.2.4` and try again?

**Comment by Shelpin** [comment]
Great! reinstalling now

**Comment by Shelpin** [comment]
Checked and working!
